// Schema Zod + valores por defecto del formulario de Inspección
// Socioeconómica (Fase 6) — portado de
// backend-inspecciones/admin-fed/src/components/features/inspecciones/types.ts
// (mismos nombres de campo exactos, sintaxis JS en vez de TS). Los
// nombres de campo del formulario coinciden con `nombre_maquina` de
// METADATOS_CAMPOS en el repo origen, y con las columnas reales de
// INSPECCIONES/CAP_* verificadas en vivo (ver specs/fase6_inspecciones_socioeconomicas.md §2).

import { z } from 'zod'

const str = z.string().optional().nullable()
const num = z.coerce.number().optional().nullable()

// Paridad exacta con las listas <option> reales de cada <select> —
// components/features/inspecciones/tabs/TabGeneral.jsx (Estado,
// Tipo_Inspeccion, Resultado_Global) y TabCierre.jsx (Estado,
// Resultado_Global, duplicado en la pestaña de cierre). Si se agrega una
// opción nueva al UI, agregarla aquí también — un valor fuera de esta
// lista ahora sí es rechazado por Zod antes de llegar a la base de datos,
// no solo restringido visualmente por el <select>.
const ESTADO_VALUES = ['En Proceso', 'Cerrada', 'Aprobada', 'Rechazada']
const TIPO_INSPECCION_VALUES = ['Interna', 'Externa', 'Seguimiento', 'Anunciada', 'No anunciada']
const RESULTADO_GLOBAL_VALUES = [
  'Aprobado',
  'Aprobado con observaciones',
  'No aprobado',
  'Suspendido',
]

export const inspeccionSchema = z.object({
  // ── INSPECCIONES ──────────────────────────────────────────────────
  // ID_Socio/ID_Parcela: enlace al padrón compartido (PADRON_SOCIOS/
  // PADRON_PARCELAS), llenado por el autocompletado — ver
  // components/features/inspecciones/PadronAutocomplete.jsx. No estaban
  // en el port inicial de Fase 6 (el formulario original tampoco los
  // exponía como campos editables directos).
  ID_Socio: str,
  ID_Parcela: str,
  Fecha_Visita: str,
  Inspector: z.string().min(1, 'Requerido'),
  Estado: z.enum(ESTADO_VALUES),
  Tipo_Inspeccion: z.enum(TIPO_INSPECCION_VALUES).optional().nullable().or(z.literal('')),
  GPS_Punto_Control: str,
  Resultado_Global: z.enum(RESULTADO_GLOBAL_VALUES).optional().nullable().or(z.literal('')),
  resumen_incumplimientos: str,
  comprobacion_interna: str,
  Fecha_Cierre: str,
  Firma_Productor: str,
  Firma_Inspector: str,

  // ── CAP_DATOS_SOCIO ───────────────────────────────────────────────
  socio_nombre_completo: str,
  socio_dni: str,
  socio_genero: str,
  socio_fecha_nacimiento: str,
  socio_fecha_ingreso: str,
  socio_departamento: str,
  socio_provincia: str,
  socio_distrito: str,
  localidad: str,
  estado_civil: str,
  conyuge_nombre: str,
  conyuge_dni: str,
  educacion: str,
  celular_socio: str,
  celular_smartphone: str,
  acceso_internet: str,
  redes_sociales: str,
  credito: str,
  credito_donde_otros: str,
  credito_utilizo: str,
  generacion_ingresos: str,
  porcent_ingresos_cafe: num,
  percent_ingresos_crianza_animales: num,
  percent_ingresos_comercio: num,
  percent_ingresos_construccion: num,
  percent_ingresos_transporte: num,
  percent_profesion_oficio: num,
  generacion_profesion_oficio_cual: str,
  percent_ingresos_otros_cultivo: num,
  percent_ingresos_otros: num,
  generacion_profesion_oficio_cual_otro: str,
  percent_tot: num,
  familia: num,
  familia_menores_14: num,
  familia_menores_15_18: num,
  traba_cam_tot: num,
  nro_empleado_permanente: num,
  nro_empleado_temporales: num,
  cuenta_bancaria: str,
  cuenta_bancaria_entidad: str,
  centro_salud: str,
  centro_salud_cuales: str,
  centro_salud_distanc: str,
  medio_transporte_tiene: str,
  hijos_socio: str,

  // ── CAP_MIC ───────────────────────────────────────────────────────
  semilla_propia: str,
  semilla_proviene: str,
  plant_norma_org: str,
  plant_norma_org_insum_perm: str,
  nc_plant_norma_org_insum_no_perm: str,
  manejo_sombra: str,
  benef_humedo: str,
  benef_humedo_ob: str,
  benef_humedo_estado: str,
  tanque_tina: str,
  tanque_tina_tipo: str,
  tanque_tina_estado: str,
  pulpero: str,
  pulpero_tipo: str,
  pulpero_estado: str,
  manejo_aguas_mieles_practica: str,
  manejo_aguas_mieles_estado: str,
  nva_areas_adecuadas: str,
  pract_plagenf: str,
  pract_plagenf_cuales: str,
  abonom: str,
  insumo_perm_org: str,
  diversif_cultivos: str,
  diversif_cultivos_det: str,
  fertilidad: str,
  men_mic: num,
  may_mic: num,
  total_puntaje_mic: num,

  // ── CAP_CONSERVACION ──────────────────────────────────────────────
  extr_agua_sup: str,
  sepacion_areas: str,
  conoce_proh_bosq_nat: str,
  conoce_proh_bosq_nat_ue: str,
  vida_silv_ret: str,
  vida_silv_no_emp: str,
  especies: str,
  especies_medidas: str,
  fauna: str,
  fauna_especies: str,
  fauna_medidas: str,
  acciones_proteccion: str,
  acciones_proteccion_manera: str,
  areas_produccion: str,
  areas_produccion_ob: str,
  program_ecosist: str,
  proteccion_fuentes: str,
  proteccion_fuentes_ob: str,
  men_conser: num,
  may_conser: num,
  total_puntaje_conser: num,

  // ── CAP_BIENESTAR ─────────────────────────────────────────────────
  condiciones_bienestar: str,
  condiciones_bienestar_ob: str,
  condiciones_bienestar_mat: str,
  agua_consumo: str,
  agua_consumo_cuales: str,
  personal_monto: str,
  personal_monto_ob: str,
  personal_monto_ob_otro: str,
  horas_trabajo: str,
  descanso_trabajo: str,
  monitoreo_menores: str,
  medicamentos: str,
  medicamentos_lista: str,
  practica_discriminatoria: str,
  practica_discriminatoria_ob: str,
  discrimin_raza_rel_sex: str,
  discrimin_raza_rel_sex_ob: str,
  menores_trabajando: str,
  menores_trabajando_edades: str,
  registro_trabajadores: str,
  quejas_reclamaciones: str,
  discapac_temporal_trab: str,
  discapac_temporal_trab_ob: str,
  program_salud: str,
  capacit_trab_prot: str,
  posee_epp: str,
  accidentes: str,
  senalizacion_peligro: str,
  nomas_seguridad: str,
  emergencia: str,
  situaciones_peligro: str,
  act_no_riesgo: str,
  obl_bien: num,
  may_bien: num,
  men_bien: num,
  total_puntaje_bien: num,

  // ── CAP_RIESGOS ───────────────────────────────────────────────────
  conoce_uso_estiercoles_fresco: str,
  insumos_no_permit: str,
  insumos_no_permit_que_encontro: str,
  tala: str,
  tala_ob: str,
  contaminacion: str,
  contaminacion_ob: str,
  prev_mez_prod: str,
  obs_no_mezcla_contam: str,
  producc_paralela: str,
  obs_paralela: str,
  implem_medidas: str,
  secado: str,
  secado_cuales: str,
  secado_condic: str,
  almacenam: str,
  almacenam_condic: str,
  condic_oper: str,
  levantamiento_nc: str,
  levantamiento_estado: str,
  men_riesgo: num,
  may_riesgo: num,
  obl_riesgo: num,
  total_puntaje_riesgo: num,

  // ── CAP_GESTION ───────────────────────────────────────────────────
  cronog_finca: str,
  cronog_finca_estado: str,
  registros: str,
  visita_asist_tecnica: str,
  temas_asist_tec: str,
  temas_asist_tec_nc: str,
  croquis: str,
  croquis_tipo: str,
  prima_cj: str,
  prima_cj_des: str,
  uso_fuente_energia: str,
  uso_fuente_energia_tipo: str,
  asistio_capacitacion: str,
  asistio_capacitacion_num: num,
  invierte_finca: str,
  invierte_finca_actividades: str,
  invierte_finca_actividades_otros: str,
  ingresos_venta_producto: str,
  ingresos_venta_producto_monto: str,
  directivos: str,
  procedimiento_reclamo: str,
  riesgos_gest: str,
  men_gest: num,
  may_gest: num,
  total_puntaje_gest: num,
})

export const DEFAULT_VALUES = {
  // INSPECCIONES
  ID_Socio: '',
  ID_Parcela: '',
  Fecha_Visita: '',
  Inspector: '',
  Estado: 'En Proceso',
  Tipo_Inspeccion: '',
  GPS_Punto_Control: '',
  Resultado_Global: '',
  resumen_incumplimientos: '',
  comprobacion_interna: '',
  Fecha_Cierre: '',
  Firma_Productor: '',
  Firma_Inspector: '',
  // CAP_DATOS_SOCIO
  socio_nombre_completo: '',
  socio_dni: '',
  socio_genero: '',
  socio_fecha_nacimiento: '',
  socio_fecha_ingreso: '',
  socio_departamento: '',
  socio_provincia: '',
  socio_distrito: '',
  localidad: '',
  estado_civil: '',
  conyuge_nombre: '',
  conyuge_dni: '',
  educacion: '',
  celular_socio: '',
  celular_smartphone: '',
  acceso_internet: '',
  redes_sociales: '',
  credito: '',
  credito_donde_otros: '',
  credito_utilizo: '',
  generacion_ingresos: '',
  porcent_ingresos_cafe: null,
  percent_ingresos_crianza_animales: null,
  percent_ingresos_comercio: null,
  percent_ingresos_construccion: null,
  percent_ingresos_transporte: null,
  percent_profesion_oficio: null,
  generacion_profesion_oficio_cual: '',
  percent_ingresos_otros_cultivo: null,
  percent_ingresos_otros: null,
  generacion_profesion_oficio_cual_otro: '',
  percent_tot: null,
  familia: null,
  familia_menores_14: null,
  familia_menores_15_18: null,
  traba_cam_tot: null,
  nro_empleado_permanente: null,
  nro_empleado_temporales: null,
  cuenta_bancaria: '',
  cuenta_bancaria_entidad: '',
  centro_salud: '',
  centro_salud_cuales: '',
  centro_salud_distanc: '',
  medio_transporte_tiene: '',
  hijos_socio: '',
  // CAP_MIC
  semilla_propia: '',
  semilla_proviene: '',
  plant_norma_org: '',
  plant_norma_org_insum_perm: '',
  nc_plant_norma_org_insum_no_perm: '',
  manejo_sombra: '',
  benef_humedo: '',
  benef_humedo_ob: '',
  benef_humedo_estado: '',
  tanque_tina: '',
  tanque_tina_tipo: '',
  tanque_tina_estado: '',
  pulpero: '',
  pulpero_tipo: '',
  pulpero_estado: '',
  manejo_aguas_mieles_practica: '',
  manejo_aguas_mieles_estado: '',
  nva_areas_adecuadas: '',
  pract_plagenf: '',
  pract_plagenf_cuales: '',
  abonom: '',
  insumo_perm_org: '',
  diversif_cultivos: '',
  diversif_cultivos_det: '',
  fertilidad: '',
  men_mic: null,
  may_mic: null,
  total_puntaje_mic: null,
  // CAP_CONSERVACION
  extr_agua_sup: '',
  sepacion_areas: '',
  conoce_proh_bosq_nat: '',
  conoce_proh_bosq_nat_ue: '',
  vida_silv_ret: '',
  vida_silv_no_emp: '',
  especies: '',
  especies_medidas: '',
  fauna: '',
  fauna_especies: '',
  fauna_medidas: '',
  acciones_proteccion: '',
  acciones_proteccion_manera: '',
  areas_produccion: '',
  areas_produccion_ob: '',
  program_ecosist: '',
  proteccion_fuentes: '',
  proteccion_fuentes_ob: '',
  men_conser: null,
  may_conser: null,
  total_puntaje_conser: null,
  // CAP_BIENESTAR
  condiciones_bienestar: '',
  condiciones_bienestar_ob: '',
  condiciones_bienestar_mat: '',
  agua_consumo: '',
  agua_consumo_cuales: '',
  personal_monto: '',
  personal_monto_ob: '',
  personal_monto_ob_otro: '',
  horas_trabajo: '',
  descanso_trabajo: '',
  monitoreo_menores: '',
  medicamentos: '',
  medicamentos_lista: '',
  practica_discriminatoria: '',
  practica_discriminatoria_ob: '',
  discrimin_raza_rel_sex: '',
  discrimin_raza_rel_sex_ob: '',
  menores_trabajando: '',
  menores_trabajando_edades: '',
  registro_trabajadores: '',
  quejas_reclamaciones: '',
  discapac_temporal_trab: '',
  discapac_temporal_trab_ob: '',
  program_salud: '',
  capacit_trab_prot: '',
  posee_epp: '',
  accidentes: '',
  senalizacion_peligro: '',
  nomas_seguridad: '',
  emergencia: '',
  situaciones_peligro: '',
  act_no_riesgo: '',
  obl_bien: null,
  may_bien: null,
  men_bien: null,
  total_puntaje_bien: null,
  // CAP_RIESGOS
  conoce_uso_estiercoles_fresco: '',
  insumos_no_permit: '',
  insumos_no_permit_que_encontro: '',
  tala: '',
  tala_ob: '',
  contaminacion: '',
  contaminacion_ob: '',
  prev_mez_prod: '',
  obs_no_mezcla_contam: '',
  producc_paralela: '',
  obs_paralela: '',
  implem_medidas: '',
  secado: '',
  secado_cuales: '',
  secado_condic: '',
  almacenam: '',
  almacenam_condic: '',
  condic_oper: '',
  levantamiento_nc: '',
  levantamiento_estado: '',
  men_riesgo: null,
  may_riesgo: null,
  obl_riesgo: null,
  total_puntaje_riesgo: null,
  // CAP_GESTION
  cronog_finca: '',
  cronog_finca_estado: '',
  registros: '',
  visita_asist_tecnica: '',
  temas_asist_tec: '',
  temas_asist_tec_nc: '',
  croquis: '',
  croquis_tipo: '',
  prima_cj: '',
  prima_cj_des: '',
  uso_fuente_energia: '',
  uso_fuente_energia_tipo: '',
  asistio_capacitacion: '',
  asistio_capacitacion_num: null,
  invierte_finca: '',
  invierte_finca_actividades: '',
  invierte_finca_actividades_otros: '',
  ingresos_venta_producto: '',
  ingresos_venta_producto_monto: '',
  directivos: '',
  procedimiento_reclamo: '',
  riesgos_gest: '',
  men_gest: null,
  may_gest: null,
  total_puntaje_gest: null,
}
